
<table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="410" id="AutoNumber1">
  <tr>
    <td><b><font class="headingfont"><center>August Contest</center></font></b>
    <table><tr height=2><td></td></tr></table>
    <font class="textfont">Everyone likes free things and we want to make everyone 
    happy, so this month we've decided to give away a free PC Game.&nbsp; The lucky 
    winner will be able to choose any game from one of the following titles and we'll 
    package it up and ship them the game all for <B>FREE</b>!
    </font><BR>
    <p><font class="textfont">The games up for grabs this month are:<br>
    - Gangsters 2<br>
    - Startopia<br>
    - Alone in the Dark 4<br>
    - I War 2: Edge of Chaos<br>
    - Desperados<br></font></p>
    <p><font class="textfont">During the month of August, every <b>$50</b> you spend 
    at Deliverance Software gives you one entry into the draw.&nbsp; Your totals are 
    cumulative, so if you spend $75 today you'll receive one entry and if you spend $75 
    a week later you'll receive two more entries ($75 + $75 = $150).</font></p>
    <p><font class="textfont">The contest runs from August 1st until August 31st and 
    the winner will be announced on our website no later than September 3rd.</font></p>
    <p><font class="textfont">Now for the inevitable rules and regulations:</font><br>
    <font class="textfont" size="8">- Pre-order purchases are only eligible if they are 
    paid for during the period that the contest runs (August 1st - August 31st)<br>
    - This contest is only open to residents of Australia and Deliverance Software 
    Pty Ltd will not ship the selected game outside of Australia<br>
    - The winner will be notified by email on September 1st and must make their selection 
    in email to "admin@deliverance.com.au" by no later than September 14th.&nbsp; A 
    failure to meet this deadline will result in a re-draw of the remaining contestants 
    on September 15th and a new winner will be announced and contacted<br>
    - In the unlikely event that the game selected from the above list is no longer 
    available, the winner will be asked to choose from the remaining games on the list<br>
    - Deliverance Software Pty Ltd reserves the right to change the games on the list 
    at any time should the listed games become unavailable via our normal distribution 
    channels<br>
    - Deliverance Software Pty Ltd  ACN 096 502 617&nbsp; ABN 57 096 502 617<br>
    </font></p>
    </td>
  </tr>
</table>
<BR><BR>
<hr size="1" align="center" width="80%" >
<center><a href='<%=AppendQuery("games.asp")%>' class="links" >Home</a></center>
