
<table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="100%" id="AutoNumber1">
  <tr>
    <td><b><font class="headingfont"><center>Customer Support</center></font></b>
    <table><tr height=2><td></td></tr></table>
    <font class="textfont">Customer Service is an area of our business 
    where we are always looking to improve.&nbsp; Our goals are to make the 
    purchasing of games online as simple, secure and rewarding as possible for 
    our customers.</font>
    <br> <br> <br><br>
    <a name="contactfeedback"><b><font class="highlightfont"><center>Contact and Feedback Information</center></font></b></a>
    <br><font class="textfont">At Deliverance Software, we want our 
    customers to be able to contact us whenever they need to should the need 
    arise.&nbsp; The best way to reach us at all times is by email.&nbsp; If you 
    have a general comment or some feedback you would like to give us, please 
    send it to:</font><br><br>
    <font class="textfont">
    <b><a class="textfontlinks" href="mailto:feedback@deliverance.com.au">
    feedback@deliverance.com.au</a></b><br><br>
    </font>
    <font class="textfont">If you have any questions about any 
    aspect of our site or business, please send those to:</font><p>
    <font class="textfont"><b><a class="textfontlinks" href="mailto:help@deliverance.com.au">
    help@deliverance.com.au</a></b></font><br><br>
    <font class="textfont">We make a 
    serious effort to respond to all email within 12 hours of receiving them.</font><p>
    &nbsp;<p>
    <a name="checkorder"><b><font class="highlightfont"><center>Check Your Order Status</center></font></b></a><p>
    <font class="textfont">One of the difficult parts about shopping online 
    is the idea of paying for something with your credit card and then having to 
    wait a certain period of time before that product arrives.&nbsp; A large 
    part of the shopping experience is paying for something and taking it with 
    you.&nbsp; As hard as we may try, we can't overcome that, but we can try and 
    keep you updated about the status of your order.&nbsp; Throughout the 
    lifecycle of your order, our systems will send you email telling you at what 
    stage we're at.&nbsp; We also provide the means for you to track the order 
    yourself on any page at our site.&nbsp; Simply click on the <b>
    <a class="textfontlinks" href="<%=AppendQuery("logintrackorder.asp")%>">Track Order</a></b> 
    link and enter the details of your order and away you go.</font></td>
  </tr>
</table>
<BR><BR>
<hr size="1" align="center" width="80%" >
<center><a href='<%=AppendQuery("games.asp")%>' class="links" >Home</a></center>
